# Generated by Django 5.1 on 2026-08-04 18:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atenciones', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Código de estudiante')),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='DNI')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('escuela', models.CharField(choices=[('SISTEMAS', 'Ingeniería de Sistemas'), ('CIVIL', 'Ingeniería Civil'), ('AMBIENTAL', 'Ingeniería Ambiental y Sanitaria'), ('ELECTRONICA', 'Ingeniería Electrónica'), ('ENFERMERIA', 'Enfermería'), ('OBSTETRICIA', 'Obstetricia'), ('EDUCACION', 'Educación'), ('DERECHO', 'Derecho y Ciencias Políticas')], max_length=15, verbose_name='Escuela profesional')),
                ('ciclo', models.PositiveSmallIntegerField(verbose_name='Ciclo')),
                ('correo_institucional', models.EmailField(blank=True, max_length=254, verbose_name='Correo institucional')),
                ('matriculado', models.BooleanField(default=True, verbose_name='Matrícula activa')),
                ('paciente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiante', to='pacientes.paciente', verbose_name='Ficha de paciente')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiante', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de usuario')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes (padrón)',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('motivo', models.TextField(verbose_name='Motivo de la consulta')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=12, verbose_name='Estado')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='Creada en')),
                ('atencion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita', to='atenciones.atencion', verbose_name='Atención generada')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='portal.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha', 'hora'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'CONFIRMADA'])), fields=('fecha', 'hora'), name='cita_unica_por_slot_activo')],
            },
        ),
    ]
