# Generated by Django 5.1 on 2026-08-04 17:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de atención')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de consulta')),
                ('anamnesis', models.TextField(blank=True, verbose_name='Anamnesis')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(blank=True, verbose_name='Tratamiento / indicaciones')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('nivel_triage', models.CharField(choices=[('ROJO', 'Rojo — Emergencia'), ('NARANJA', 'Naranja — Urgente'), ('AMARILLO', 'Amarillo — Prioridad media'), ('VERDE', 'Verde — Prioridad baja'), ('AZUL', 'Azul — No urgente')], default='AMARILLO', max_length=10, verbose_name='Nivel de triage')),
                ('estado', models.CharField(choices=[('EN_ESPERA', 'En espera'), ('EN_ATENCION', 'En atención'), ('ATENDIDO', 'Atendido'), ('DERIVADO', 'Derivado')], default='EN_ESPERA', max_length=12, verbose_name='Estado')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Médico / personal de salud')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Atención',
                'verbose_name_plural': 'Atenciones',
                'ordering': ['-fecha_atencion'],
            },
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('presion_sistolica', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Presión sistólica (mmHg)')),
                ('presion_diastolica', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Presión diastólica (mmHg)')),
                ('pulso', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pulso (lpm)')),
                ('frecuencia_respiratoria', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Frecuencia respiratoria (rpm)')),
                ('saturacion_oxigeno', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Saturación de oxígeno (%)')),
                ('peso', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('talla', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Talla (cm)')),
                ('registrado_en', models.DateTimeField(auto_now_add=True, verbose_name='Registrado en')),
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='atenciones.atencion', verbose_name='Atención')),
            ],
            options={
                'verbose_name': 'Signos vitales',
                'verbose_name_plural': 'Signos vitales',
            },
        ),
    ]
