# Generated by Django 5.1 on 2026-08-17 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atenciones', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetamedicamento',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='inventario.medicamento', verbose_name='Medicamento'),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='atencion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='atenciones.atencion', verbose_name='Atención'),
        ),
    ]
