# Generated by Django 5.1 on 2026-08-05 15:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('indicaciones', models.CharField(blank=True, max_length=200, verbose_name='Indicaciones')),
                ('registrado_en', models.DateTimeField(auto_now_add=True, verbose_name='Registrado en')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='atenciones.atencion', verbose_name='Atención')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='inventario.medicamento', verbose_name='Medicamento')),
            ],
            options={
                'verbose_name': 'Ítem de receta',
                'verbose_name_plural': 'Ítems de receta',
                'ordering': ['registrado_en'],
            },
        ),
    ]
