# Generated by Django 5.1 on 2026-08-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0002_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recetamedicamento',
            unique_together={('atencion', 'medicamento')},
        ),
    ]
