# Generated by Django 5.1 on 2026-08-04 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MEDICO', 'Médico'), ('ENFERMERO', 'Enfermero(a)'), ('FARMACEUTICO', 'Farmacéutico(a)'), ('ADMIN', 'Administrador'), ('ESTUDIANTE', 'Estudiante')], default='ENFERMERO', max_length=20, verbose_name='Rol')),
                ('colegiatura', models.CharField(blank=True, max_length=30, verbose_name='N° de colegiatura')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['user__first_name'],
            },
        ),
    ]
